import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Wrapper from "./components/layout/wrapper/layout";
import Navbar from "./components/layout/navbar/navbar";
import Footer from "./components/layout/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Wrapper>{children}</Wrapper>
        <Footer />
      </body>
    </html>
  );
}
