import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import Wrapper from "./layout/wrapper/layout";
import Navbar from "./layout/navbar/navbar";
import Footer from "./layout/footer/footer";
import "../styles/Main.scss";
import Template from "./Template";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={publicSans.className}>
        {/* <Navbar />
        <Wrapper>{children}</Wrapper>
        <Footer /> */}
        <Template />
      </body>
    </html>
  );
}
